apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-bakery-workbench-front
  namespace: ui-bakery
spec:
  selector:
    matchLabels:
      app: ui-bakery-workbench-front
  template:
    metadata:
      labels:
        app: ui-bakery-workbench-front
    spec:
      containers:
      - name: ui-bakery-workbench-front
        image: cruibakeryonprem.azurecr.io/cloud/workbench-front:latest
        envFrom:
          - configMapRef:
              name: ui-bakery-configmap
        resources:
          requests:
            memory: "128Mi"
            cpu: "120m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 30
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workbench-front
  namespace: ui-bakery
spec:
  type: ClusterIP
  selector:
    app: ui-bakery-workbench-front
  ports:
  - port: 8080
    targetPort: 8080
